### ISSUE TITLE
No rainbow

### ISSUE THREAD

**Issue by traviss0** [ewendlick/ulam_spiral_js#1]
![screen shot 2018-09-13 at 16 13 30](https://user-images.githubusercontent.com/12059973/45472883-790e4a80-b770-11e8-8085-05e79d0a4a56.png)

**Comment by ewendlick** [comment]
Everyone here are making very good points. These issues will be addressed in the order that I read them.




I am not going to read these.

**Comment by ewendlick** [comment]
I lied. I actually read through these comments. Half of them were quite helpful.
Fun rainbow colors have been confirmed as working.
